[Tengineコンソールの詳細設計・実装] Tengine::Event, Tengine::Core::Event の属性名が変更となったので修正しました。画面のテストが落ちていたので修正しましたが、後２つテストが落ちてしまいます。中途半端ですが一旦コミットします。
Failures:

  1) Tengine::Core::EventsController GET index assigns all tengine_core_events as @tengine_core_events
     Failure/Error: events.to_a.should eq([event])
       
       expected [#<Tengine::Core::Event _id: 4e6dd2f347d17c6c6000001e, _type: nil, event_type_name: nil, key: nil, source_name: nil, occurred_at: nil, level: 1, confirmed: nil, sender_name: nil, properties: nil>]
            got []
       
       (compared using ==)
       
       Diff:
       @@ -1,2 +1,2 @@
       -[#<Tengine::Core::Event _id: 4e6dd2f347d17c6c6000001e, _type: nil, event_type_name: nil, key: nil, source_name: nil, occurred_at: nil, level: 1, confirmed: nil, sender_name: nil, properties: nil>]
       +[]
     # ./spec/controllers/tengine/core/events_controller_spec.rb:37:in `block (3 levels) in <top (required)>'

  2) tengine/core/events/index.html.erb renders a list of tengine_core_events
     Failure/Error: render
     ActionView::Template::Error:
       undefined method `enum_base_name' for NilClass:Class
     # ./app/views/tengine/core/events/index.html.erb:28:in `block in _app_views_tengine_core_events_index_html_erb__1672710075473314302_70133367663840'
     # ./app/views/tengine/core/events/index.html.erb:5:in `_app_views_tengine_core_events_index_html_erb__1672710075473314302_70133367663840'
     # ./spec/views/tengine/core/events/index.html.erb_spec.rb:28:in `block (2 levels) in <top (required)>'

Finished in 13.3 seconds
267 examples, 2 failures

Failed examples:

rspec ./spec/controllers/tengine/core/events_controller_spec.rb:31 # Tengine::Core::EventsController GET index assigns all tengine_core_events as @tengine_core_events
rspec ./spec/views/tengine/core/events/index.html.erb_spec.rb:27 # tengine/core/events/index.html.erb renders a list of tengine_core_events
rake aborted!