[ユースケースからフィーチャを作成できることを確認する] rake spec実行時に以下のエラーが出たのでAR用の設定をコメントアウトしました。
/Users/akima/tengine/tengine_console/spec/spec_helper.rb:21:in `block in <top (required)>': undefined method `fixture_path=' for #<RSpec::Core::Configuration:0x00000100ce0d28> (NoMethodError)

/Users/akima/tengine/tengine_console/spec/spec_helper.rb:26:in `block in <top (required)>': undefined method `use_transactional_fixtures=' for #<RSpec::Core::Configuration:0x000001024393a8> (NoMethodError)